### ISSUE TITLE
How to add command ? 

### ISSUE THREAD

**Issue by MatthD** [mmkal/handy-redis#176]
Thanks for the project, I am trying to use this package & add command to be able to store json data, it seems that I something like 

```javascript
const redis = createHandyClient({ host: 'localhost', port: 6379, db: 0 });
redis.redis.add_command('json.set');
redis.json_set('test', 42)
```
Should work but I have an error 'redis.redis.add_command is not a function'

**Comment by mmkal** [comment]
I haven't used that feature before. Maybe this would work?

```js
const orig = createHandyClient({ host: 'localhost', port: 6379, db: 0 });
orig.redis.add_command('json.set');
const redis = createHandyClient(orig.redis);
redis.json_set('test', 42);
```

When creating a client, the constructors wraps all methods on `client.__proto__`, so depending on how `add_command` affects the underlying client, that might work at runtime. But you won't get any types, so you'd still probably be better off falling back to `client.redis.json_set`.

**Comment by mmkal** [comment]
@MatthD I looked into this - I think the problem you were having was that `add_command` is a static export of the `'redis'` module rather than a method on the client. In v2 you can now add commands that aren't in `node_redis`, see [the release notes](https://github.com/mmkal/handy-redis/releases/tag/v2.0.0)/readme for details.
