### ISSUE TITLE
wrong direction in npm page

### ISSUE THREAD

**Issue by lumosmind** [mmkal/handy-redis#272]
in npm page at top-right side
`npm i handy-redis`

but in documentation
`npm install handy-redis redis`

why don't you put redis into dependencies ?

or make all installing instructions like
`npm install handy-redis redis`

**Comment by mmkal** [comment]
The `npm i handy-redis` instruction in the top right of the npm page is part of npmjs.com and isn't controlled by this package. 

The reasons `redis` isn't in dependencies:
- to allow users to more easily install different versions. This library is mostly types, the runtime is very light.
- In future node_redis might not be the only kind of underlying client. I'm trying out [ioredis](https://github.com/mmkal/handy-redis/discussions/260) and might add deno support in future.

Is there some way you think the instructions should be clearer? I'd consider making it a peer dependency. I've held off on this so far because in my experience they're more headache than they're worth, with the current landscape of package managers.

**Comment by lumosmind** [comment]
I can understand. You want to create generic solution. But there is well known principle "Single Responsibility". 
You can create different packages for node_redis and ioredis as kind of abstraction layers . These abstraction layers use your generic solution as dependency under the hood. So your download rate increase with other two abstraction packages. And usage of these packages could be easy.

**Comment by mmkal** [comment]
Sure. I think "easy usage" is a good goal. I want to be sure it's as convenient to use as possible, so I agree it might be preferable to publish a separate package for ioredis (or deno) rather than let them pollute the API surface. So far they haven't IMO, even in the [proposal PR](#241).

If `npm i handy-redis redis` vs `npm i handy-redis` is the _only_ extra work required, it's not a very high price to pay. Arguably it's actually beneficial, as it makes sure users are aware what they're using under the hood. If there are any other problems you've found with usage though, let me know and I'll look into them.

**Comment by lumosmind** [comment]
Maybe you can improve readme.md file to get attention of developers. Because they can think the package has some problems until read all of the readme.md file.
