### ISSUE TITLE
zrangebyscore doesn't allow +inf/-inf

### ISSUE THREAD

**Issue by mateuszlewko** [mmkal/handy-redis#30]
Type definitions of some redis commands are not complete. For example here is type definition for 
`zrangebyscore(key: string, min: number, max: number, withscores: "WITHSCORES", offset_count: ["LIMIT", number, number]): Promise<any[]>;`
`Min` and `max` arguments accept only number, where node_redis could also accept string or just "+inf" | "-inf".

**Comment by mmkal** [comment]
What's the use case? You should be able to use JavaScript's `-Infinty` and `Infinty` keywords. They have `number` type in typescript.

Using strings for number-typed arguments is exactly the sort of thing this library is supposed to protect against, unless you've found something you're unable to do. This works, and IMO is better than using `"-inf"`/`"+inf"`:

```typescript
it("zrangebyscore with infinite limits", async () => {
    const client = createHandyClient();
    await client.zadd("myzset", [1, "one"], [2, "two"], [3, "three"], [-Number.MAX_VALUE, "lowest"], [Number.MAX_VALUE, "highest"]);

    const all = await client.zrangebyscore("myzset", -Infinity, Infinity);
    expect(all).toEqual(["lowest", "one", "two", "three", "highest"]);

    const positives = await client.zrangebyscore("myzset", 0, Infinity);
    expect(positives).toEqual(["one", "two", "three", "highest"]);

    const negatives = await client.zrangebyscore("myzset", -Infinity, 0);
    expect(negatives).toEqual(["lowest"]);
});
```

**Comment by mmkal** [comment]
That's a good point, if redis and javascript used different float implementations using `Infinty` possibly wouldn't work anymore. Right now the typings are automatically generated from [redis-doc's command.json](https://github.com/antirez/redis-doc/blob/1aa2882aecd31b410bc4cc0b09fbcf25700228ab/commands.json) (otherwise this project would be very hard to maintain). But the redis-doc just lists `max` and `min` as `double`: https://github.com/antirez/redis-doc/blob/1aa2882aecd31b410bc4cc0b09fbcf25700228ab/commands.json#L2877-L2884

So possibly this issue should be moved to that repo - since it's _not_ actually a double. It's a double, or `-inf`, or `+inf`, or in fact open ranges like `(123`. That last one will be very hard to model in a non-hacky way in typescript, without resorting to `string`. Most `double` values in commands.json don't allow those special values because they're not limits. I can't off the top of my head think of a clean way to separate `min`/`max` from, say, the increment amount in [`incrbyfloat`](https://github.com/antirez/redis-doc/blob/1aa2882aecd31b410bc4cc0b09fbcf25700228ab/commands.json#L1324). Open to suggestions though.
