### ISSUE TITLE
`batch` method is missing

### ISSUE THREAD

**Issue by zdila** [mmkal/handy-redis#45]
`batch` method is missing

**Comment by mmkal** [comment]
I'm not familiar with this and don't see it in the redis docs. Do you have a link, or what you'd expect this method to look like?

**Comment by zdila** [comment]
Please see https://www.npmjs.com/package/redis#clientbatchcommands

**Comment by mmkal** [comment]
Ah, this is part of the `redis` npm package rather than redis itself. That's still available via the `.redis` property on a client created with this package. I haven't used batch, so if you give me an idea of what it'd look like I can let you know if it's something I could work on; or I could point you in the right direction for a PR.

**Comment by zdila** [comment]
`batch` in redis npm package has exactly the same API as `multi` just different name.

**Comment by mmkal** [comment]
@zdila batch is now supported in [v2](https://github.com/mmkal/handy-redis/releases/tag/v2.0.0)
